# Generated by Django 2.2.7 on 2019-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_training_sharedorgnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='sharedorgnotes',
            field=models.URLField(blank=True, help_text='Shared documents (e.g., Google Drive Document/Folder, Sharepoint site, etc.)'),
        ),
    ]
