# Generated by Django 2.2.7 on 2019-12-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20191204_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='lead',
            field=models.IntegerField(choices=[(1, 'Hub'), (2, 'SCO'), (3, 'AST'), (4, 'SME'), (5, 'Support Team'), (6, 'Partner'), (7, 'Contractor'), (8, 'Other')], default=1, help_text='Type of organization leading the event'),
        ),
    ]
