# Generated by Django 2.1.5 on 2020-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20200214_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourcetype',
            field=models.IntegerField(choices=[(1, 'Training Agenda'), (2, 'Training Notes'), (3, 'Document'), (4, 'Presentation'), (5, 'Exercise guide'), (6, 'Tutorial'), (7, 'Video'), (8, 'Audio'), (9, 'Script'), (10, 'Dataset'), (11, 'External website'), (12, 'Photo/Photo gallery'), (13, 'Debrief'), (0, 'Other')], default=1, help_text='Resource Type'),
        ),
    ]
