# Generated by Django 2.1.5 on 2020-03-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20200214_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service Name (According to the Service Catalog)', max_length=300)),
                ('serviceCatalogID', models.CharField(blank=True, help_text='Service Catalog ID', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servicearea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service Area Name', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='servicearea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Servicearea'),
        ),
    ]
