# Generated by Django 3.0.3 on 2020-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_training_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='recordstatus',
            field=models.IntegerField(choices=[(0, 'Draft/test'), (1, 'Work in Progress'), (2, 'Registration Complete')], default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='serviceareas',
            field=models.ManyToManyField(blank=True, to='training.Servicearea'),
        ),
        migrations.AlterField(
            model_name='training',
            name='services',
            field=models.ManyToManyField(blank=True, to='training.Service'),
        ),
        migrations.AlterField(
            model_name='training',
            name='starts',
            field=models.DateField(blank=True),
        ),
    ]
