# Generated by Django 3.0.8 on 2020-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20200717_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='hub_region',
            field=models.CharField(help_text='Region Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='hub',
            name='hub_short_name',
            field=models.CharField(help_text='Hub Short Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='hub',
            name='org_address',
            field=models.CharField(blank=True, help_text='Postal Address', max_length=500),
        ),
        migrations.AlterField(
            model_name='hub',
            name='org_phone',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=20),
        ),
    ]
