# Generated by Django 3.0.8 on 2020-07-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20200717_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='hub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.Hub'),
        ),
    ]
