# Generated by Django 3.0.8 on 2020-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20200717_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dataType', models.IntegerField(blank=True, choices=[(0, 'Other/not specified'), (1, 'EO Sensor'), (2, 'Model')])),
                ('accessType', models.IntegerField(blank=True, choices=[(0, 'Other/not specified'), (1, 'Public/Open Source'), (2, 'Commercial'), (3, 'Restricted by Originator')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='training',
            name='dataSource',
            field=models.ManyToManyField(blank=True, help_text='Data sources used in the training', to='training.DataSource'),
        ),
    ]
