# Generated by Django 3.0.8 on 2020-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20200723_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attendance_females',
            field=models.IntegerField(blank=True, help_text='Number of female participants', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='attendance_males',
            field=models.IntegerField(blank=True, help_text='Number of male participants', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='attendance_not_specified',
            field=models.IntegerField(blank=True, help_text='Number of participants (gender not specified)', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='attendance_sheet',
            field=models.FileField(blank=True, help_text='Provide spreadsheet (if not available, leave blank and provide numbers below)', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
