# Generated by Django 3.0.8 on 2020-07-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20200727_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='attendance_females',
            new_name='attendanceFemales',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='attendance_males',
            new_name='attendanceMales',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='attendance_not_specified',
            new_name='attendanceNot_specified',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='attendance_sheet',
            new_name='attendanceSheet',
        ),
        migrations.RemoveField(
            model_name='training',
            name='organization',
        ),
        migrations.AlterField(
            model_name='training',
            name='hub',
            field=models.ForeignKey(default=1, help_text='Organizer (hub)', on_delete=django.db.models.deletion.CASCADE, to='training.Hub'),
        ),
    ]
