# Generated by Django 3.0.8 on 2020-07-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20200727_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='attendanceNot_specified',
            new_name='attendanceNotSpecified',
        ),
    ]
