# Generated by Django 3.1.1 on 2020-10-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_auto_20200727_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsreference',
            name='trainings',
            field=models.ManyToManyField(blank=True, help_text='Related Training Events', to='training.Training'),
        ),
        migrations.AddField(
            model_name='resource',
            name='trainings',
            field=models.ManyToManyField(blank=True, help_text='Related Training Events', to='training.Training'),
        ),
        migrations.AlterField(
            model_name='training',
            name='attendanceSheet',
            field=models.FileField(blank=True, help_text='NOT FUNCTIONAL YET. Will be used to upload spreadsheet', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
