# Generated by Django 3.1.1 on 2021-01-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20201005_1210'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='participantorganization',
        #     unique_together={('name', 'country')},
        # ),
    ]
