# Generated by Django 3.1.1 on 2021-01-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_auto_20210108_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not specified')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not specified')], default='X', max_length=1),
        ),
    ]
