# Generated by Django 3.1.1 on 2021-02-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20210119_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
