# Generated by Django 3.1.1 on 2021-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_auto_20210204_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='city',
            field=models.CharField(blank=True, help_text='Only required for in-person events', max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='country',
            field=models.CharField(blank=True, help_text='For virtual events, enter primary target location', max_length=100),
        ),
    ]
