# Generated by Django 3.1.1 on 2021-02-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_auto_20210226_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='newsreferences',
        ),
        migrations.DeleteModel(
            name='Newsreference',
        ),
    ]
