# Generated by Django 3.1.1 on 2021-02-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_auto_20210226_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='attendanceSheet',
        ),
    ]
