# Generated by Django 3.1.1 on 2021-02-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_remove_training_attendancesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='postsurvey',
        ),
        migrations.RemoveField(
            model_name='training',
            name='presurvey',
        ),
    ]
