# Generated by Django 3.1.1 on 2021-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0032_auto_20210304_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantorganization',
            name='acronym',
            field=models.CharField(blank=True, default='-- NOT SPECIFIED --', max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainingorganization',
            field=models.ManyToManyField(blank=True, help_text='Participating Organizations (Trainers)', related_name='training_orgs', to='training.Participantorganization'),
        ),
    ]
