# Generated by Django 3.1.1 on 2021-03-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_auto_20210304_1010'),
        ('training', '0032_auto_20210304_1608'),
    ]

    operations = [
    ]
