# Generated by Django 3.1.1 on 2021-03-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_merge_20210304_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='starts',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='participantorganization',
            unique_together={('name', 'country')},
        ),
    ]
