# Generated by Django 3.2 on 2021-05-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_auto_20210312_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'permissions': [('can_upload_csv', 'Can upload CSV')]},
        ),
    ]
