# Generated by Django 3.2.4 on 2021-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_alter_training_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='license',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Specified'), (1, 'CC Attribution'), (2, 'CC Attribution-ShareAlike'), (3, 'CC Attribution-NoDerivs'), (4, 'CC Attribution-NonCommercial'), (5, 'CC Attribution-NonCommercial-ShareAlike'), (6, 'CC Attribution-NonCommercial-NoDerivs'), (7, 'MIT'), (8, 'GNU GPLv3'), (9, 'Unlicense')], default=0, help_text='Applicable license for the resource'),
            preserve_default=False,
        ),
    ]
