# Generated by Django 3.2.4 on 2021-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_resource_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='license',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Specified'), (1, 'NOT LICENSED'), (2, 'CC Attribution'), (3, 'CC Attribution-ShareAlike'), (4, 'CC Attribution-NoDerivs'), (5, 'CC Attribution-NonCommercial'), (6, 'CC Attribution-NonCommercial-ShareAlike'), (7, 'CC Attribution-NonCommercial-NoDerivs'), (8, 'MIT'), (9, 'GNU GPLv3'), (10, 'Unlicense'), (11, 'Other')], help_text='Applicable license for the resource'),
        ),
    ]
