# Generated by Django 3.2.4 on 2022-06-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_alter_resource_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainings',
            field=models.ManyToManyField(blank=True, help_text='Training events', to='training.Training'),
        ),
    ]
