# Generated by Django 3.2.4 on 2022-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0041_trainer_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantorganization',
            name='training_participation',
            field=models.ManyToManyField(blank=True, related_name='training', to='training.Training'),
        ),
    ]
