# Generated by Django 3.2.4 on 2022-06-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0042_participantorganization_training_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantorganization',
            name='training_participation',
        ),
        migrations.AddField(
            model_name='participantorganization',
            name='trainee_participation',
            field=models.ManyToManyField(blank=True, help_text='Participated as Trainees', to='training.Training'),
        ),
        migrations.AddField(
            model_name='participantorganization',
            name='trainer_participation',
            field=models.ManyToManyField(blank=True, help_text='Participated as Trainer', related_name='trainer_participation', to='training.Training'),
        ),
    ]
