# Generated by Django 4.0.4 on 2025-01-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0043_auto_20220629_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='shown',
            field=models.BooleanField(default=True),
        ),
    ]
